# Generated by Django 5.0.7 on 2024-08-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('PLAYER_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=100)),
                ('POSITION', models.CharField(max_length=10)),
                ('CMP', models.FloatField(blank=True, null=True)),
                ('PASS_ATT', models.FloatField(blank=True, null=True)),
                ('PASS_PCT', models.FloatField(blank=True, null=True)),
                ('PASS_YDS', models.FloatField(blank=True, null=True)),
                ('PASS_YPA', models.FloatField(blank=True, null=True)),
                ('PASS_TD', models.FloatField(blank=True, null=True)),
                ('INT', models.FloatField(blank=True, null=True)),
                ('SACKS', models.FloatField(blank=True, null=True)),
                ('RUSH_ATT', models.FloatField(blank=True, null=True)),
                ('RUSH_YDS', models.FloatField(blank=True, null=True)),
                ('RUSH_YPA', models.FloatField(blank=True, null=True)),
                ('RUSH_LG', models.FloatField(blank=True, null=True)),
                ('RUSH_20', models.FloatField(blank=True, null=True)),
                ('RUSH_TD', models.FloatField(blank=True, null=True)),
                ('REC', models.FloatField(blank=True, null=True)),
                ('TGT', models.FloatField(blank=True, null=True)),
                ('REC_YDS', models.FloatField(blank=True, null=True)),
                ('REC_LG', models.FloatField(blank=True, null=True)),
                ('REC_20', models.FloatField(blank=True, null=True)),
                ('YPR', models.FloatField(blank=True, null=True)),
                ('REC_TD', models.FloatField(blank=True, null=True)),
                ('FL', models.FloatField(blank=True, null=True)),
                ('G', models.FloatField(blank=True, null=True)),
                ('FPTS_G', models.FloatField(blank=True, null=True)),
                ('OVERALL_PTS', models.FloatField(blank=True, null=True)),
                ('PPR', models.FloatField(blank=True, null=True)),
                ('PPR_G', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'player_projections',
                'managed': False,
            },
        ),
    ]
